# -*- coding: utf-8 -*-
"""metrics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/cu-student-comsc-colab-cmt307/locations/europe-west4/repositories/5ca0f9dd-88b5-4cf9-b5b8-49402881e7f0
"""

import numpy as np

def rmsle(y_true, y_pred):
  return np.sqrt(np.mean((np.log1p(y_pred) - np.log1p(y_true)) ** 2))